# Generated by Django 2.2.12 on 2020-05-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('year', models.SmallIntegerField()),
                ('gearbox', models.SmallIntegerField(choices=[(0, 'механика'), (1, 'автомат'), (2, 'робот')], default=0)),
                ('color', models.CharField(default='white', max_length=20)),
            ],
        ),
    ]
