# Generated by Django 2.2.12 on 2020-05-14 01:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.PositiveIntegerField(default=app.models.random_color),
        ),
    ]
