# Generated by Django 2.2.12 on 2020-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200514_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.SmallIntegerField(choices=[(0, 'механика'), (1, 'автомат'), (2, 'робот')], default=0),
        ),
    ]
