# Generated by Django 2.2.12 on 2020-05-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200514_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='vendor',
            field=models.CharField(max_length=40),
        ),
    ]
